packages/serverless-contracts/contracts/apiGateway/__tests__/httpApiContract.test.ts
packages/serverless-contracts/contracts/apiGateway/__tests__/restApiContract.test.ts
packages/serverless-contracts/contracts/apiGateway/apiGatewayContract.ts
packages/serverless-contracts/contracts/apiGateway/types.ts

Prevent having unknown keys to infered types:
```typescript
const bodySchema = {
type: 'object',
properties: {
productId: { type: 'string' },
},
required: ['productId'],
additionalProperties: false,
} as const;
const createRentalContract = new ApiGatewayContract({
id: 'users-getUser',
path: '/checkout/rentals',
method: 'POST',
integrationType: 'httpApi',
pathParametersSchema: undefined,
queryStringParametersSchema: undefined,
bodySchema,
headersSchema: undefined,
outputSchema: undefined,
});
export type CreateRentalContractInput = FromSchema<typeof createRentalContract.inputSchema>;
// before
type CreateRentalContractInput = {
[x: string]: unknown;
body: {
productId: string;
};
}
// after
type CreateRentalContractInput = {
body: {
productId: string;
};
}
```

Prevent additionalProperties in api gateway schemas

---

package.json
yarn.lock

Release https://github.com/nrwl/nx/releases/tag/13.9.3 remove the nx cli
from @nrwl/cli.
We need to explicitly add the nx dependency now.

fix(nx): make nx command work again

---

backend/orchestrator/package.json
packages/serverless-configuration/src/sharedConfig.ts
user-docs/cloudfront/package.json
user-docs/cloudfront/serverless.ts
user-docs/cloudfront/tsconfig.json
yarn.lock

This PR add per-stage support to deploy documentation to cloudfront. The issue here is that for some environments we need empty variables and for the moment it is not possible with Serverless.
I'll check what we can do

feat(user-docs): add stage params for static website construct

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/fetchRequest.test.ts
packages/serverless-contracts/src/contracts/apiGateway/features/fetchRequest.ts

Fixes #208 
The problem came from the fact that new URL validate the url format and require it to start with http:// etc
So now, if baseUrl is not defined, we don't use the URL class and we concatenate the path and the query params manually

fix(contracts): prevent using URL class to build fetch path with no base url

---

packages/serverless-contracts/src/contracts/apiGateway/features/httpLambdaHandler.ts
packages/serverless-contracts/src/contracts/apiGateway/types/common.ts

We currently only validate the body for an Api Gateway contract. However, we easily have the ability to validate the whole event with `contract.inputSchema`

feat(serverless-contracts): validate whole input event

---

release.sh

For now we have an issue during the release process as the newly published version of `@swarmion` packages are not available to the `yarn up` command.
This command should clean the cache and fix this issue.

chore(release): clean yarn cache after publishing packages

---

user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md

Hey guys,
As per HTTP/2 spec, requests' headers must be lowercase. However, since type-inference is case-sensitive in typescript, we may encouter errors when having a header defined like this (with uppercase letter(s)):
Here, when using `getHttpLambdaHandler` from a contract with such headers, ajv looks for a `myHeader` key but in HTTP/2, curl defaults to lowercasing all headers which leads to a validation error.
This is just a proposition as swarmion's doc is not supposed to be about http standards, but I thought this example was a bit misleading.

Doc: add info on header case in http/2

---

packages/serverless-contracts/src/contracts/apiGateway/__mocks__/requestContext.ts
packages/serverless-contracts/src/contracts/apiGateway/__tests__/httpLambdaHandler.test.ts
packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.test.ts
packages/serverless-contracts/src/contracts/apiGateway/features/httpLambdaHandler.ts
packages/serverless-contracts/src/contracts/apiGateway/types/lambdaHandler.ts
user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md

In order to make my lambdas completly functional, I would need to pass additional arguments to my lambda handler other than the event (for example using the initialisation context of the lambda). This is currently not possible.
The desired behavior is:
```ts
const handler = getHttpLambdaHandler(myContract)(async (
event, // type inference is ok
toto = "tata" // with a default value
) => {
// handler body
}
);
```
This PR adds this possibility and documents it

feat(serverless-contracts): add `context` and `callback` support

---

packages/create-swarmion-app/package.json
packages/serverless-contracts/src/contracts/apiGateway/__tests__/httpLambdaHandler.test.ts
packages/serverless-contracts/src/contracts/apiGateway/utils/apiGatewayProxyTransformers.ts

feat(serverless-contracts): add Content-Type header to getHandler response

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/fetchRequest.test.ts
packages/serverless-contracts/src/contracts/apiGateway/features/requestParameters.ts

This adds management of undefined queryStringParameters values in getFetchRequest and resolves #271

fix: add undefined queryStringParameters values management in getFetchRequest

---

backend/orchestrator/serverless.ts
examples/swarmion-full-stack/backend/core/serverless.ts
examples/swarmion-full-stack/backend/users/serverless.ts
examples/swarmion-full-stack/frontend/cloudfront/serverless.ts
examples/swarmion-starter/backend/core/serverless.ts
packages/nx-plugin/src/generators/service/files/serverless.ts__tmpl__
user-docs/cloudfront/serverless.ts

This property is unsused and may confuse users, especially since the use of the `custom` key is not recommended (although `serverless-esbuild` uses it :/

fix(serverless): rename unused custom property projectName

---

examples/swarmion-full-stack/frontend/app/src/theme/muiTheme.ts

A weird `createTheme_default is not a function` appears when importing `createTheme` from `@mui/material/styles`.
The problem is known by the community and has a simple fix, which is in this PR
- Issue on material-ui repo : https://github.com/mui/material-ui/issues/31835
- (N.B.: OP thinks this is an "issue with esbuild" but it is also reproducible with vite)
- Comment suggesting fix : https://github.com/mui/material-ui/issues/31835#issuecomment-1147055123
I checked that there is no other such import in the swarmion repo.

fix mui import in muiTheme.ts

---

packages/serverless-helpers/src/helpers/__tests__/mergeStageParams.test.ts
packages/serverless-helpers/src/helpers/applyHttpMiddlewares.ts
packages/serverless-helpers/src/helpers/getCdkHandlerPath.ts
packages/serverless-helpers/src/helpers/getEnvVariable.ts
packages/serverless-helpers/src/helpers/getHandlerPath.ts
packages/serverless-helpers/src/helpers/index.ts
packages/serverless-helpers/src/helpers/mergeStageParams.ts
packages/serverless-helpers/src/helpers/testFunctionNames.ts

We currently have a `getHandlerPath` that works for the Serverless Framework. However the CDK requires the file to have the `ts` extension and not the handler name.
This PR adds this feature.
It may be used as such:
```
const myLambda = new NodejsFunction(this, 'Lambda', {
entry: getCdkHandlerPath(__dirname),
handler: 'main',
runtime: Runtime.NODEJS_16_X,
architecture: Architecture.ARM_64,
awsSdkConnectionReuse: true,
bundling: sharedEsbuildConfig,
environment: {
...
},
});
```

feat(serverless-helpers): add getCdkhandlerPath

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/fetchRequest.test.ts
packages/serverless-contracts/src/contracts/apiGateway/features/requestParameters.ts
user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md

Fix #282.
This updates the docs to present the risks of only using `getLamdbaHandler`

docs(user-docs): update api gateway contracts to advise getHandler

---

packages/nx-plugin/src/generators/library/typed-json-config/package.json.ts

Basically, if you have this in your package.json:
```javascript
{
...
"clean": "pnpm clean"
// or
"clean": "yarn clean"
...
}
```
Launching the clean command will loop forever and crash your computer. This PR fixes exactly that :)

fix pnpm clean loop in package.json

---

packages/serverless-contracts/package.json
pnpm-lock.yaml

Fix suggestion to issue #330.
`pnpm run deploy` fails on newly created projects due to a missing `@aws-sdk/client-eventbridge` dependency in `@swarmion/serverless-contracts`
This MR moves `@aws-sdk/client-eventbridge` from devDependencies to dependencies in `@swarmion/serverless-contracts`

Make @aws-skd/client-eventbridge a dependency of @swarmion/serverless-contracts

---

examples/swarmion-full-stack/tsconfig.json
examples/swarmion-starter/tsconfig.json
tsconfig.json

We currently remove the comments from our .d.ts files.
This is a problem for our published libraries as they do not publish their nice JSDoc.
Also for the two starters, it seems to me that the benefits of removing comments is non-existent since we do not use `tsc` to transpile from TS to JS. On the contrary, keeping them would improve internal documentation.
Check out https://github.com/microsoft/TypeScript/issues/14619 for more context.
WDYT?

chore: keep comments in .d.ts files

---

packages/serverless-contracts/src/contracts/apiGateway/types/constants.ts

Improve Api Gateway authorizers
-  add support for `aws_iam` authorizer for both `httpApi` and `restApi`.

feat(serverless-contracts): add support for `aws_iam` authorizer for both `httpApi` and `restApi`

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaTrigger.test.ts
packages/serverless-contracts/src/contracts/apiGateway/types/lambdaTrigger.ts

Following #358, there was a typing error on our `restApi` triggers.
This PR fixes this issue and improves trigger tests for `ApiGatewayContract`

fix(serverless-contracts): fix trigger type for restApi + add tests

---

packages/serverless-configuration/package.json
packages/serverless-configuration/src/sharedConfig.ts
packages/serverless-configuration/tsconfig.json
packages/serverless-helpers/package.json
packages/serverless-helpers/src/configuration/esbuildConfig.ts
packages/serverless-helpers/src/configuration/index.ts
packages/serverless-helpers/src/helpers/__tests__/getCdkHandlerPath.test.ts
packages/serverless-helpers/src/helpers/__tests__/getHandlerPath.test.ts
packages/serverless-helpers/src/helpers/getCdkHandlerPath.ts
packages/serverless-helpers/src/helpers/getHandlerPath.ts
packages/serverless-helpers/src/index.ts
pnpm-lock.yaml

This PR adds two new features:
- export a default esbuild config from `serverless-helpers`. This can reduce the boilerplate on the Swarmion projects and can enable us to keep it up-to-date for everyone.
- improve the `getCdkHandlerPath` with optional arguments to override `fileName` and `extension`. This is useful in environments where you need to include js handlers directly in your CDK config.
@adriencaccia WDYT?

feat(serverless-helpers): export esbuild config and improve getCdkHandlerPath

---

.github/workflows/pr.yml

ci: remove test-unit from shared job in ci

---

examples/swarmion-with-next/frontend/next-app/.env.example
examples/swarmion-with-next/frontend/next-app/.gitignore
examples/swarmion-with-next/frontend/next-app/README.md
examples/swarmion-with-next/frontend/next-app/cdk.json
examples/swarmion-with-next/frontend/next-app/hosting/bin.ts
examples/swarmion-with-next/frontend/next-app/hosting/settings/branchSettings.ts
examples/swarmion-with-next/frontend/next-app/hosting/settings/buildSettings.ts
examples/swarmion-with-next/frontend/next-app/hosting/settings/environmentVariables.ts
examples/swarmion-with-next/frontend/next-app/hosting/settings/sourceCodeProvider.ts
examples/swarmion-with-next/frontend/next-app/hosting/stack.ts
examples/swarmion-with-next/frontend/next-app/package.json
examples/swarmion-with-next/frontend/next-app/tsconfig.cdk.json
examples/swarmion-with-next/nx.json
examples/swarmion-with-next/pnpm-lock.yaml

Reopen PR #363
Starting from `feat/swarmion-with-next` branch, I added an option to deploy the NextJs 13 app to Amplify, with a CDK construct.
See the updated README for more details on setup and use.
Thanks to @alexandrepernin who first deployed a POC of this new deployment option!

Add Amplify deployment to NextJs example [reopened]

---

.github/actions/install-node-deps/action.yml
examples/swarmion-full-stack/.github/workflows/merge-main.yml
examples/swarmion-full-stack/.github/workflows/pr.yml
examples/swarmion-starter/.github/workflows/merge-main.yml
examples/swarmion-starter/.github/workflows/pr.yml
examples/swarmion-with-next/.github/workflows/merge-main.yml
examples/swarmion-with-next/.github/workflows/pr.yml

"version" is optional and by default, gets the version from package.json See https://github.com/pnpm/action-setup\#version

chore: remove explicit pnpm version from CI

---

backend/orchestrator/serverless.ts
packages/serverless-configuration/src/sharedConfig.ts
packages/serverless-helpers/src/types/serverless.ts

This is a first PR in order to tackle #445 
Export a type for the serverless provider config.
Next step is using it in the examples

feat(serverless-helpers): export serverless provider type

---

.github/workflows/push-main.yml

Related issue: https://github.com/actions/runner/issues/2205

ci: make sure deploy is working when validate-tests is skipped

---

packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
packages/serverless-contracts/src/contracts/eventBridge/features/lambdaHandler.ts

This change allows to compile the schema only once, instead of compiling it on every invocation.
On handlers with basic schemas, this change reduces the execution by around 5ms.
With larger schemas, the difference is even more significant.

perf(serverless-contracts): move ajv schema compilation outside of handler invocation

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.test.ts
packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.type.test.ts
packages/serverless-contracts/src/contracts/apiGateway/types/apiGateway.ts
packages/serverless-contracts/src/contracts/apiGateway/types/authorizerContext.ts
packages/serverless-contracts/src/contracts/apiGateway/types/index.ts
packages/serverless-contracts/src/contracts/apiGateway/types/lambdaHandler.ts

Not sure about the addition in unit tests in addition to the type test, I can remove it

feat(serverless-contracts): Add type helper to extract event type from contract

---

packages/nx-plugin/schemas/cdk-service/files/cdk.json__tmpl__
packages/nx-plugin/src/generators/cdk-service/typed-json-config/package.json.ts
packages/nx-plugin/src/generators/helpers/normalizeOptions.ts
packages/nx-plugin/src/generators/types/Shema.ts

fixes #491 
The idea of this fix is:
- each stack gets its bootstrap stack named `CDKToolkit{projectName}`
- each bootstrap stack uses a `qualifier` to ensure resources won't clash
- this `qualifier` must be explicitely passed to `cdk bootstrap`, otherwise it is not applied
- this `qualifier` must be less than 10 chars, so a SHA1 hash is enough
See https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html

feat(nx-plugin): add qualifier to cdk generator

---

packages/nx-plugin/schemas/cdk-service/files/contracts/healthContract.ts__tmpl__
packages/nx-plugin/schemas/cdk-service/files/functions/health/config.ts__tmpl__

Using `resourceForPath` is much more scalable than `addResource` because:
- it can add nested paths (e.g. `/toto/tata/{tataId}`)
- it supports a path beginning with `/`

feat(nx-plugin): use resourceForPath for CDK construct

---

packages/nx-plugin/src/generators/helpers/normalizeOptions.ts

I got an error when bootstraping a new stack due to the presence of `/` in the qualifier. It is safer if we use a `base64url` instead of `base64`. See [this stackoverflow](https://stackoverflow.com/questions/55389211/string-based-data-encoding-base64-vs-base64url) for detailed differences.
Also I have checked that `-` is safe in a qualifier.

fix(nx-plugin): use safe base64url for qualifier

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/httpLambdaHandler.test.ts
packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
packages/serverless-contracts/src/contracts/eventBridge/__tests__/lambdaHandler.test.ts
packages/serverless-contracts/src/contracts/eventBridge/features/lambdaHandler.ts
packages/serverless-contracts/src/features/lambdaHandler.ts
user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md
user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/2-eventbridge.md

feat(serverless-contracts): add an optional arg in getHandler to disable input/output validation

---

packages/serverless-contracts/src/contracts/apiGateway/index.ts

fix(serverless-contracts): remove mock handler export

---

.github/workflows/pr.yml

fixes #532 
- Add a check on `merge_group` event as suggested in the [merge queue documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#:~:text=update%20your%20CI%20configuration%20to%20trigger%20and%20report%20on%20merge%20group%20events)
The `validate-pr` job of the `PR Tests` workflow is the only required check

feat: add tests workflow to merge group check

---

examples/swarmion-bare/package.json
examples/swarmion-full-stack/package.json
examples/swarmion-starter/package.json
examples/swarmion-with-next/package.json
scripts/check-example.sh

It was needed only when running install inside the Swarmion repo,
so it should not present in the examples files that will be downloaded.
Using `HUSKY=0` when running commands triggering `postinstall` does the trick.

examples: remove useless postinstall variable check

---

packages/serverless-contracts/package.json

With pnpm, A peerDependency error will be triggered if the consumer has an incompatible version of one of the peerDependencies.

feat(serverless-contracts): make serverless and axios optional peerdeps

---

examples/swarmion-bare/package.json

Hey I add an error with ESLint import rule when I created a project from `bare`. It couldn't find a contracts directory because it wasn't created.
This fixed for me

fix(bare template): remove unnecessary workspaces

---

packages/serverless-configuration/src/sharedConfig.ts

`http://` is mandatory in CORS to deploy httpApi
fix https://github.com/swarmion/swarmion/issues/582

chore(serverless-configuration): fix apiGatewayCorsAllowedOrigins

---

packages/nx-plugin/src/generators/helpers/normalizeOptions.ts

fix https://github.com/swarmion/swarmion/issues/615
use `hex` encoding to create a `hashedProjectName` that matches `/^[a-z0-9]{10}$/` and avoid side effects caused by not supported special characters

fix(nx-plugin): create hashedProjectName without special characters

---

packages/serverless-contracts/src/contracts/apiGateway/features/fetchRequest.ts
packages/serverless-contracts/src/contracts/apiGateway/utils/__tests__/combineUrls.test.ts
packages/serverless-contracts/src/contracts/apiGateway/utils/combineUrls.ts
packages/serverless-contracts/src/contracts/apiGateway/utils/index.ts

this is a fix proposal for issue #464, based on the url combining used by axios

fix(serverless-contracts): combine baseUrl and path correctly in fetchRequests

---

pnpm-lock.yaml
services/orchestrator/package.json
services/orchestrator/serverless.ts

Should we also add it to the examples ? Or is it not worth it ?

Add better credentials plugin to orchestrator service

---

.github/workflows/pr-check-examples.yml
.github/workflows/pr.yml
.github/workflows/push-main.yml

Whenever a workflow is manually cancelled, this makes more sense to not run the validation jobs. Also, if these were successful, a deployment could be trigerred while the workflow was cancelled.

ci: do not run 'validate' jobs if the workflow is cancelled

---

packages/serverless-contracts/src/contracts/apiGateway/__tests__/openApiDocumentation.test.ts
packages/serverless-contracts/src/contracts/apiGateway/features/openApiDocumentation.ts
packages/serverless-contracts/src/features/__tests__/openApiDocumentation.test.ts

Hello guys!
I'd like to use the header params in the Swagger docs, so i added this little addition to your code.
Hopefully you guys won't mind it!

feat: add header parameters to open api documentation generation

---

.eslintrc.js
packages/serverless-cdk-plugin/src/serverlessCdk.ts
packages/serverless-contracts-plugin/src/plugin/utils/listLocalContractSchemas.ts
packages/serverless-contracts/codspeed-variance.md
packages/serverless-contracts/src/contracts/apiGateway/apiGatewayContract.ts
packages/serverless-contracts/src/contracts/apiGateway/features/fullContractSchema.ts
packages/serverless-contracts/src/contracts/apiGateway/features/openApiDocumentation.ts
packages/serverless-contracts/src/contracts/apiGateway/features/requestParameters.ts
packages/serverless-contracts/src/contracts/apiGateway/utils/convertJsonSchemaToValidOAS3.ts

I had the following bug when trying to build my `sst` app:
```
pnpm sst build
Error: Cannot find module '/Users/adrien/projects/swarmion/swarmion/packages/serverless-contracts/node_modules/lodash/isUndefined' imported from /Users/adrien/projects/swarmion/swarmion/packages/serverless-contracts/dist/index.js
Did you mean to import lodash@4.17.21/node_modules/lodash/isUndefined.js?
Trace: Error: Cannot find module '/Users/adrien/projects/swarmion/swarmion/packages/serverless-contracts/node_modules/lodash/isUndefined' imported from /Users/adrien/projects/swarmion/swarmion/packages/serverless-contracts/dist/index.js
Did you mean to import lodash@4.17.21/node_modules/lodash/isUndefined.js?
at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
at new NodeError …
```

fix(lodash): enforce lodash imports to use .js extension

---

packages/serverless-contracts/package.json
pnpm-lock.yaml

Reverts swarmion/swarmion#1124
I believe tsx v4 is incompatible with serverless-framework
cf https://github.com/swarmion/swarmion/pull/808#issuecomment-1833392426

Revert "fix(serverless-contracts): update dependency tsx to v4"

---

.prettierignore
README.md
packages/nx-plugin/src/generators/cdk-service/typed-json-config/package.json.ts
packages/nx-plugin/src/generators/helpers/getWorkspaceDependencyVersion.ts
packages/nx-plugin/src/generators/helpers/index.ts
packages/nx-plugin/src/generators/helpers/versions.ts
packages/nx-plugin/src/generators/library/typed-json-config/package.json.ts
packages/nx-plugin/src/generators/service/typed-json-config/package.json.ts
scripts/check-example.sh

This improves the way new package versions are generated by the plugin. We used to have `latest` by default, which can cause sudden issues when a new major version is released and we are not ready (for example, eslint v9 requires some config rework, and we can't push it directly if the rest of the repo is not migrated.
In this new version, we resolve the current version of the package and only fallback on `latest` if we found no match.
This will also unblock all PRs currently blocked by the merge train 🙃

feat(nx-plugin): use current workspace dependency versions instead of latest
