backend/orchestrator/jest.config.ts, packages/configuration/src/config/jest.config.ts, packages/serverless-contracts/jest.config.ts
See https://github.com/swarmion/template/pull/138
=> feat: use moduleDirectories option in jest to avoid moduleNameMapper pain

packages/nx-plugin/src/generators/helpers/index.ts, packages/nx-plugin/src/generators/helpers/packageGenerator.ts, packages/nx-plugin/src/generators/helpers/updateRootPackageJson.ts, user-docs/documentation/docs/code-structure/nx-plugin.md
- feat(nx-plugin): add doc
- fix: add nx-plugin links in doc
- feat: add directory to the yarn workspace
=> Feat: add directory to yarn workspaces

.yarnrc.yml
https://yarnpkg.com/configuration/yarnrc#logFilters
https://yarnpkg.com/advanced/error-codes#yn0076---incompatible_architecture
=> chore(yarn): discard compatibility warnings

.eslintrc.js
Resolves #106 
Hi @fargito ! Here's a small PR to solve aws-sdk v2 imports issue ✨ 🚀 .
have a good one!
=> feat: adding eslint rule for aws-sdk v2 imports

package.json
See https://github.com/swarmion/template/pull/182
=> chore: remove global watch command

swarmion.code-workspace
https://github.com/TastefulElk/iam-legend/pull/18
=> chore(vscode): add iam-legend extenstion

nx.json, packages/nx-plugin/src/generators/library/typed-json-config/package.json.ts
See https://github.com/swarmion/template/pull/188
=> fix(generator): restrict depcruise to src in libraries

packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.test.ts
=> test(serverless-contracts): add undefined authorizer test case for lambda handler

.all-contributorsrc, README.md
As we are stripping the template of all unnecessary code, we need to credit the template contributors here. Many thanks to them!
=> docs: migrate contributors from template

packages/serverless-contracts/src/contracts/apiGateway/__tests__/fetchRequest.test.ts, packages/serverless-contracts/src/contracts/apiGateway/features/fetchRequest.ts, packages/serverless-contracts/src/contracts/apiGateway/features/index.ts, packages/serverless-contracts/src/contracts/apiGateway/index.ts, user-docs/documentation/docs/contracts/api-gateway.md
Should close https://github.com/swarmion/swarmion/issues/37
=> feat(contracts): add getFetchRequest feature for api gateway contract

package.json, packages/serverless-helpers/README.md, packages/serverless-helpers/package.json
Fix: https://github.com/swarmion/swarmion/issues/166
=> feat(helpers): publish serverless helpers

packages/nx-plugin/src/generators/service/files/functions/health/config.ts__tmpl__, packages/nx-plugin/src/generators/service/files/serverless.test.ts__tmpl__, packages/nx-plugin/src/generators/service/typed-json-config/package.json.ts, packages/nx-plugin/src/generators/service/typed-json-config/tsconfig.json.ts
=> fix(nx-plugin): use swarmion helpers instead of legacy workspace helpers

packages/serverless-cdk-plugin/integrationTests/defaultUsage/serverless.ts, packages/serverless-cdk-plugin/integrationTests/missingConstruct/customCdk.test.ts, packages/serverless-cdk-plugin/integrationTests/missingConstruct/serverless.ts, packages/serverless-cdk-plugin/integrationTests/wrongConstruct/customCdk.test.ts, packages/serverless-cdk-plugin/integrationTests/wrongConstruct/serverless.ts, packages/serverless-cdk-plugin/src/index.ts, packages/serverless-cdk-plugin/src/serverlessCdk.ts, packages/serverless-cdk-plugin/src/types.ts
- feat(sls-cdk-plugin): add cdk mappings to serverless configuration
- chore(sls-cdk-plugin): improve serverlessConfigFile validation
- feat(sls-cdk-plugin): declare topLevel cdkConstruct property
=> feat(serverless-cdk-plugin): improve plugin schema

.eslintrc.js, examples/swarmion-starter/.eslintrc.js, examples/swarmion-starter/backend/core/serverless.test.ts, examples/swarmion-starter/backend/core/serverless.ts, examples/swarmion-starter/package.json, packages/create-swarmion-app/src/helpers/examples.ts, packages/create-swarmion-app/src/helpers/git.ts, packages/create-swarmion-app/src/index.ts
Fixes https://github.com/swarmion/swarmion/issues/204
Fixes https://github.com/swarmion/swarmion/issues/202
=> chore: update eslint config

packages/nx-plugin/src/generators/service/typed-json-config/package.json.ts
=> Fix(nx-plugin) : add `serverless-iam-roles-per-function` dependency to services generated

package.json, release.sh
=> chore: add release script

examples/swarmion-starter/packages/serverless-configuration/src/sharedConfig.ts, packages/serverless-configuration/src/sharedConfig.ts
=> feat(shared-config): set direct deployment method as default shared provider config

backend/orchestrator/functions/requestSyncDeployment/config.ts, packages/serverless-contracts/package.json, packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaTrigger.test.ts, packages/serverless-contracts/src/contracts/apiGateway/apiGatewayContract.ts, packages/serverless-contracts/src/contracts/apiGateway/features/lambdaTrigger.ts, packages/serverless-contracts/src/contracts/apiGateway/types/lambdaTrigger.ts, packages/serverless-contracts/src/types/utilities.ts, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md, yarn.lock
=> feat(serverless-contracts): use authorizerType to enforce authorizer in lambda config

packages/serverless-contracts/README.md, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md
There was a broken link, and I thought the documentation needed a bit more information on how to leverage the `@swarmion/serverless-contracts` package 😄
=> Improve docs regarding api gateway contracts

packages/nx-plugin/src/generators/service/typed-json-config/tsconfig.json.ts
From #245 we do need this anymore
=> fix(generators): remove outdated configuration from tsconfig

examples/swarmion-full-stack/contracts/core-contracts/package.json, examples/swarmion-full-stack/contracts/users-contracts/package.json, examples/swarmion-full-stack/frontend/shared/package.json, examples/swarmion-full-stack/nx.json, examples/swarmion-full-stack/package.json, examples/swarmion-full-stack/packages/serverless-configuration/package.json, examples/swarmion-starter/contracts/core-contracts/package.json, examples/swarmion-starter/nx.json, examples/swarmion-starter/packages/serverless-configuration/package.json, packages/nx-plugin/src/generators/library/typed-json-config/package.json.ts
- fix(examples/swarmion-full-stack): add lint-fix-all script
- fix(examples): tidy nx configuration
- feat(nx-plugin): remove useless nx property
=> Fix pnpm installation

examples/swarmion-full-stack/tsconfig.json, examples/swarmion-starter/tsconfig.json, packages/create-swarmion-app/src/index.ts, packages/serverless-cdk-plugin/integrationTests/defaultUsage/customCdk.test.ts, packages/serverless-cdk-plugin/integrationTests/defaultUsage/myConstruct.ts, packages/serverless-contracts-plugin/src/plugin/utils/artifactDirectory.ts, packages/serverless-contracts-plugin/src/plugin/utils/getLatestDeployedTimestamp.ts, packages/serverless-contracts-plugin/src/plugin/utils/validateDeployment.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/httpLambdaHandler.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.test.ts, packages/serverless-contracts/src/contracts/apiGateway/features/openApiDocumentation.ts, tsconfig.json
=> Feat: add `noUncheckedIndexedAccess` typescript rule

contracts/orchestrator-contracts/package.json, examples/swarmion-full-stack/contracts/core-contracts/package.json, examples/swarmion-full-stack/contracts/users-contracts/package.json, examples/swarmion-full-stack/frontend/shared/package.json, examples/swarmion-full-stack/packages/serverless-configuration/package.json, examples/swarmion-full-stack/pnpm-lock.yaml, examples/swarmion-starter/contracts/core-contracts/package.json, examples/swarmion-starter/packages/serverless-configuration/package.json, examples/swarmion-starter/pnpm-lock.yaml, packages/create-swarmion-app/package.json, packages/eslint-plugin/package.json, packages/nx-plugin/package.json, packages/nx-plugin/src/generators/library/typed-json-config/package.json.ts, packages/serverless-cdk-plugin/package.json, packages/serverless-configuration/package.json, packages/serverless-contracts-plugin/package.json, packages/serverless-contracts/package.json, packages/serverless-helpers/package.json, pnpm-lock.yaml
=> feat: use rimraf insead of rm -rf for cross os compatibility

.github/workflows/pr-simple.yml, examples/swarmion-full-stack/.github/workflows/merge-main.yml, examples/swarmion-full-stack/backend/core/package.json, examples/swarmion-full-stack/frontend/cloudfront/package.json, examples/swarmion-starter/.github/workflows/merge-main.yml, examples/swarmion-starter/backend/core/package.json, packages/create-swarmion-app/src/create-app.ts, packages/create-swarmion-app/src/getProjectPath.ts, packages/create-swarmion-app/src/getProjectTemplate.ts, packages/create-swarmion-app/src/getRef.ts, packages/create-swarmion-app/src/helpers/examples.ts, packages/create-swarmion-app/src/helpers/renameProject.ts, packages/create-swarmion-app/src/index.ts, packages/create-swarmion-app/src/notifyUpdate.ts, packages/create-swarmion-app/src/templates.ts, scripts/check-examples.sh
=> Add CD on examples + run create-swarmion-app and test generated apps in repo CI

packages/serverless-contracts/src/contracts/apiGateway/utils/apiGatewayProxyTransformers.ts
- @LouisPinsard: Discussed with @Sc0ra about it pull request this implementation seems easier.
What do you think @fargito  ?
We didn't yet tested deeply the implementation proposal.
Would be happy to implement if needed !
=> fix: replace queryStringParameters undefined by empty object

packages/serverless-contracts/src/contracts/apiGateway/apiGatewayContract.ts, packages/serverless-contracts/src/contracts/cloudFormation/cloudFormationContract.ts, packages/serverless-contracts/src/contracts/eventBridge/eventBridgeContract.ts
=> Add inline doc for serverless-contracts

packages/create-swarmion-app/README.md, user-docs/documentation/docs/getting-started/1-generate-your-first-swarmion-project.mdx
=> docs(create-swarmion-app): only keep pnpm in create swarmion-app doc

.eslintrc.js, .github/workflows/release.yml, backend/orchestrator/tsconfig.json, changelogithub.config.ts, commitlint.config.js, examples/swarmion-full-stack/backend/core/tsconfig.json, examples/swarmion-full-stack/backend/users/tsconfig.json, examples/swarmion-full-stack/frontend/cloudfront/tsconfig.json, examples/swarmion-full-stack/tsconfig.options.json, examples/swarmion-starter/backend/core/tsconfig.json, examples/swarmion-starter/tsconfig.options.json, package.json, packages/nx-plugin/src/generators/service/typed-json-config/tsconfig.json.ts, pnpm-lock.yaml, tsconfig.eslint.json, tsconfig.options.json, user-docs/cloudfront/tsconfig.json
Fix #356
Also adds a release workflow to automatically generate GitHub release notes on releases.
=> Fix TS module error when trying to deploy

examples/swarmion-full-stack/backend/core/package.json, examples/swarmion-full-stack/backend/users/package.json, examples/swarmion-full-stack/contracts/core-contracts/package.json, examples/swarmion-full-stack/contracts/users-contracts/package.json, examples/swarmion-full-stack/packages/serverless-configuration/package.json, examples/swarmion-starter/backend/core/package.json
The work in #157 is not reflected in the `starter` and `full-stack` examples.
This PR makes sure it is fixed.
=> examples(starter): fix linter-base-config

backend/orchestrator/functions/listDeployments/handler.ts, backend/orchestrator/functions/requestSyncDeployment/handler.ts, contracts/orchestrator-contracts/src/contracts/requests/listDeployments.ts, contracts/orchestrator-contracts/src/contracts/requests/requestSyncDeployment.ts, packages/serverless-contracts/src/contracts/apiGateway/__mocks__/httpApiGatewayContract.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/apiGatewayContract.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/apiGatewayContract.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/axiosRequest.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/fetchRequest.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/fullContractSchema.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/fullContractSchema.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/httpLambdaHandler.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaTrigger.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/openApiDocumentation.test.ts, packages/serverless-contracts/src/contracts/apiGateway/apiGatewayContract.ts, packages/serverless-contracts/src/contracts/apiGateway/features/axiosRequest.ts, packages/serverless-contracts/src/contracts/apiGateway/features/fetchRequest.ts, packages/serverless-contracts/src/contracts/apiGateway/features/fullContractSchema.ts, packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts, packages/serverless-contracts/src/contracts/apiGateway/features/openApiDocumentation.ts, packages/serverless-contracts/src/contracts/apiGateway/types/common.ts, packages/serverless-contracts/src/contracts/apiGateway/types/fullContract.ts, packages/serverless-contracts/src/contracts/apiGateway/utils/apiGatewayProxyTransformers.ts, packages/serverless-contracts/src/types/http.ts, packages/serverless-contracts/src/types/index.ts, user-docs/documentation/docs/getting-started/5-add-a-new-serverless-contract-library.mdx, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/3-additional-args.md
This is to merge new management of output schemas to alpha.
=> [alpha] - Feat/output schemas no retro

backend/orchestrator/package.json, examples/swarmion-full-stack/backend/core/package.json, examples/swarmion-full-stack/backend/users/package.json, examples/swarmion-full-stack/pnpm-lock.yaml, examples/swarmion-starter/backend/core/package.json, examples/swarmion-starter/pnpm-lock.yaml, examples/swarmion-with-next/backend/core/package.json, examples/swarmion-with-next/pnpm-lock.yaml, packages/serverless-helpers/package.json, pnpm-lock.yaml
Reverts swarmion/swarmion#468
See https://github.com/floydspace/serverless-esbuild/issues/427
=> Revert "fix(serverless-helpers): update dependency esbuild to ^0.17.0"

packages/nx-plugin/schemas/cdk-service/files/functions/health/handler.test.ts__tmpl__, services/orchestrator/functions/requestSyncDeployment/handler.test.ts
Currently, our generators don't work since #488 
This PR fixes it
=> fix(nx-plugin): improve test event in handler test

packages/serverless-contracts/package.json, packages/serverless-contracts/src/contracts/apiGateway/__tests__/mockHandlerInput.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/mockHandlerInput.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/features/index.ts, packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts, packages/serverless-contracts/src/contracts/apiGateway/features/mockHandlerInput.ts, packages/serverless-contracts/src/contracts/apiGateway/index.ts, packages/serverless-contracts/src/contracts/apiGateway/types/lambdaHandler.ts, packages/serverless-contracts/src/contracts/apiGateway/utils/mockHandlerContext.ts, pnpm-lock.yaml, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md
=> feat(serverless-contracts): get mock handler event feature

packages/serverless-contracts/src/contracts/eventBridge/__tests__/eventBridgeContract.test.ts, packages/serverless-contracts/src/contracts/eventBridge/eventBridgeContract.ts, packages/serverless-contracts/src/contracts/eventBridge/types/patterns.ts
=> feat(serverless-configuration): build patterns for eventBridge contracts

packages/serverless-contracts-plugin/package.json, pnpm-lock.yaml
=> fix: serverless contracts peer dependency

.github/workflows/pr-check-examples.yml, scripts/check-example.sh
I'm not sure this works at all...
=> chore(ci): use github sha instead of merge request event

packages/nx-plugin/src/generators/helpers/symlink.ts, packages/nx-plugin/src/generators/library/library.test.ts, user-docs/documentation/docs/how-to-guides/3-migration-guides/3-esm-first-packages.mdx, user-docs/documentation/src/css/custom.css
- docs: add macOs cjs one-liner
- docs: add custom code highlight colors
- docs: add code block for syncpack migration
- feat(nx-plugin): do not create root launch.json symlink if does not exist
=> fix migration docs and nx-plugin launch.json

.github/ISSUE_TEMPLATE /bug_report.yml, .github/ISSUE_TEMPLATE /config.yml, .github/ISSUE_TEMPLATE /feature_request.yml, CONTRIBUTING.md
Largely inspired (copied 🙈) by https://github.com/vitest-dev
=> chore: add community standards

.github/actions/unit-tests-and-sonar/action.yml, packages/serverless-contracts-plugin/src/plugin/utils/listLocalContractSchemas.ts
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> fix CI: skip sonar run if token doesn't exist

examples/swarmion-full-stack/frontend/cloudfront/serverless.ts
=> examples(full-stack): switch to spa lift construct

packages/serverless-contracts/src/contracts/apiGateway/__tests__/apiGatewayContract.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/fullContractSchema.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/__tests__/lambdaHandler.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/testUtils/__tests__/mockHandlerInput.test.ts, packages/serverless-contracts/src/contracts/apiGateway/testUtils/__tests__/mockHandlerInput.type.test.ts, packages/serverless-contracts/src/contracts/apiGateway/testUtils/mockHandlerInput.ts, packages/serverless-contracts/src/contracts/apiGateway/testUtils/utils/deepMerge.test.ts, packages/serverless-contracts/src/contracts/apiGateway/testUtils/utils/deepMerge.ts, packages/serverless-contracts/src/contracts/apiGateway/testUtils/utils/index.ts, packages/serverless-contracts/src/types/__tests__/constrainedJSONSchema.type.test.ts, packages/serverless-contracts/src/types/constrainedJSONSchema.ts, packages/serverless-contracts/src/utils/index.ts, packages/serverless-contracts/src/utils/typeAssert.ts, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md
=> fix(serverless-contracts): handle undefined fixed values in mockHandlerInput

packages/serverless-contracts/src/features/__tests__/openApiDocumentation.test.ts, packages/serverless-contracts/src/features/openApiDocumentation.ts
=> fix(serverless-contracts): correctly handle multiple methods on the same path

CONTRIBUTING.md
Generated with in part thanks to https://chat.openai.com/share/7538b618-c08d-45b7-a4ed-bb168e9c1eb0
=> chore: add release authoring documentation

.github/workflows/codspeed.yml, packages/serverless-contracts/package.json, packages/serverless-contracts/src/__benches__/index.ts, packages/serverless-contracts/src/contracts/apiGateway/__benches__/basicHttpApiHandler.bench.ts, packages/serverless-contracts/src/contracts/apiGateway/__benches__/bigHttpApiHandler.bench.ts, packages/serverless-contracts/src/contracts/apiGateway/__benches__/index.ts, packages/serverless-contracts/src/contracts/eventBridge/__benches__/basicEventBridgeHandler.bench.ts, packages/serverless-contracts/src/contracts/eventBridge/__benches__/bigEventBridgeHandler.bench.ts, packages/serverless-contracts/src/contracts/eventBridge/__benches__/index.ts, pnpm-lock.yaml
A new version of `codspeed` has been released: https://github.com/CodSpeedHQ/codspeed-node/releases/tag/v2.0.0
This PR updates the dependency and refactors some of the code to make benchmark authoring easier.
=> chore(codspeed): bump codspeed

.github/CODEOWNERS
following this suggestion https://github.com/orgs/community/discussions/23064#discussioncomment-8383923
=> chore: update CODEOWNERS for renovate-approve

packages/serverless-contracts/package.json, packages/serverless-contracts/src/contracts/SQS/__tests__/sendMessages.test.ts, packages/serverless-contracts/src/contracts/SQS/features/lambdaHandler.ts, packages/serverless-contracts/src/contracts/SQS/features/sendMessage.ts, packages/serverless-contracts/src/contracts/SQS/features/sendMessages.ts, packages/serverless-contracts/src/contracts/SQS/index.ts, packages/serverless-contracts/src/contracts/SQS/types/lambdaHandler.ts, packages/serverless-contracts/src/contracts/SQS/types/sendMessage.ts, packages/serverless-contracts/src/contracts/SQS/utils/parseRecord.ts, pnpm-lock.yaml, user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/3-sqs.md
add throughtPut control over sendMessages
\+ 
Fix https://github.com/swarmion/swarmion/issues/1190
=> feat(serverless-contracts): control sendMessages throughput

user-docs/documentation/hosting/staticSite.ts, user-docs/documentation/hosting/utils/getDomainNames.ts
This requires to change the certificate validation in the DNS records
=> chore(user-docs): add apex domain name on certificate

user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/2-eventbridge.md
=> docs(eventBridge): document getMultipleEventBridgeHandler
